#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
"""Fetch the minimum set of HIP host headers for building src/runtime_src/hip.

The XRT HIP shim library implements the HIP *host* API itself; it never needs
the AMD-GPU (amd_detail) or NVIDIA (nvidia_detail) device backends. This script
vendors only the headers required to compile the xrt_hip library and the
host-only HIP tests (which include only <hip/hip_runtime_api.h>), placing them
in the sibling ``hip/`` directory so that ``-I <this dir>`` resolves
``#include <hip/...>``.

Design goals:
  * Works with any ROCm/HIP release -- pass the tag, e.g.
        ./get_hip_headers.py --tag rocm-6.3.4
    The set of headers to vendor is discovered automatically by following the
    ``#include <hip/...>`` graph starting from hip_runtime_api.h.
  * Keeps the public headers as close to upstream as possible: they are
    downloaded verbatim, and the only modification is that device-backend
    includes (``hip/nvidia_detail/...`` and GPU-only ``hip/amd_detail/...``,
    e.g. amd_hip_runtime_pt_api.h) are commented out in place -- we do not need
    them at all.
  * The handful of amd_detail includes that supply *host* declarations
    (host_defines.h macros, hipCreateChannelDesc) are kept and satisfied with
    small host-only shims.

Re-runnable and dependency-free (Python standard library only).
"""

import argparse
import os
import re
import shutil
import sys
import urllib.error
import urllib.request

DEFAULT_REPO = "ROCm/hip"
DEFAULT_TAG = "rocm-7.2.4"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# amd_detail includes that we KEEP (and satisfy with a host-only shim) because
# they provide host-side declarations the public headers rely on. Every other
# amd_detail / nvidia_detail include is device/GPU-specific and gets commented
# out. Matching is by file basename so it is version independent.
SHIM_WHITELIST = ("host_defines.h", "amd_channel_descriptor.h")

# Any top-level directory ending in one of these is a device backend.
DETAIL_DIR_SUFFIX = ("_detail",)  # amd_detail, nvidia_detail, hcc_detail, ...

INCLUDE_RE = re.compile(r'^(\s*)#\s*include\s*[<"]hip/([^">]+)[">]')


def gen_banner(repo, tag):
    return """\
// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by src/runtime_src/hip/detail/get_hip_headers.py
// Source: github.com/{repo} @ {tag}
//
// This is a host-only shim. The AMD-GPU / NVIDIA device backends are
// intentionally excluded -- the xrt_hip library implements the HIP host API
// itself and does not compile device code. Do not edit by hand; re-run the
// script instead.
""".format(repo=repo, tag=tag)


# ---------------------------------------------------------------------------
# Fetch / IO helpers
# ---------------------------------------------------------------------------
def fetch(url):
    """Return the text body of *url* or exit with a clear message."""
    try:
        with urllib.request.urlopen(url) as resp:
            return resp.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        sys.exit("error: HTTP {code} fetching {url}".format(code=exc.code, url=url))
    except urllib.error.URLError as exc:
        sys.exit("error: cannot fetch {url}: {reason}".format(url=url, reason=exc.reason))


def write_file(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def is_detail(path):
    """True if a 'hip/<subdir>/...' include points at a device backend."""
    head = path.split("/", 1)[0]
    return any(head.endswith(sfx) for sfx in DETAIL_DIR_SUFFIX)


# ---------------------------------------------------------------------------
# Header post-processing
# ---------------------------------------------------------------------------
def process_header(text):
    """Comment out device-backend includes; collect top-level deps and shims.

    Returns (new_text, top_level_deps, kept_shims, excluded_includes).
      * top_level_deps  -- basenames of 'hip/<name>' includes to also vendor.
      * kept_shims      -- amd_detail include paths kept (need a host shim).
      * excluded_includes -- device-backend include paths commented out.
    """
    out, deps, kept_shims, excluded = [], [], [], []
    for line in text.splitlines():
        m = INCLUDE_RE.match(line)
        if not m:
            out.append(line)
            continue
        indent, path = m.group(1), m.group(2)
        base = os.path.basename(path)
        if "/" in path:
            if is_detail(path):
                if base in SHIM_WHITELIST:
                    kept_shims.append(path)
                    out.append(line)
                else:
                    out.append(indent + "// [xrt] excluded device backend: " + line.strip())
                    excluded.append(path)
            else:
                # Some other hip/ subdirectory -- keep verbatim.
                out.append(line)
        else:
            # Top-level hip/<name>. hip_version.h is generated, not downloaded.
            if base != "hip_version.h":
                deps.append(base)
            out.append(line)
    return "\n".join(out) + "\n", deps, kept_shims, excluded


# ---------------------------------------------------------------------------
# Generated content
# ---------------------------------------------------------------------------
def parse_version(version_text):
    """Parse the upstream VERSION file into (major, minor, patch) ints."""
    fields, key = {}, None
    for line in version_text.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.startswith("#"):
            key = line.lstrip("#").strip()
        elif key is not None:
            fields[key] = line
            key = None
    try:
        return (
            int(fields["HIP_VERSION_MAJOR"]),
            int(fields["HIP_VERSION_MINOR"]),
            int(fields["HIP_VERSION_PATCH"]),
        )
    except (KeyError, ValueError):
        sys.exit("error: could not parse VERSION file:\n" + version_text)


def hip_version_header(banner, major, minor, patch):
    """Reproduce upstream hip_version.h (normally generated at build time)."""
    combined = major * 10000000 + minor * 100000 + patch
    return banner + """\
#ifndef HIP_VERSION_H
#define HIP_VERSION_H

#define HIP_VERSION_MAJOR {major}
#define HIP_VERSION_MINOR {minor}
#define HIP_VERSION_PATCH {patch}
#define HIP_VERSION_GITHASH ""
#define HIP_VERSION_BUILD_ID 0
#define HIP_VERSION_BUILD_NAME ""
#define HIP_VERSION {combined}

#define HIP_VERSION_GITDATE 0

#endif // HIP_VERSION_H
""".format(major=major, minor=minor, patch=patch, combined=combined)


def shim_content(banner, base):
    """Host-only shim body for a kept amd_detail include (by basename)."""
    if base == "host_defines.h":
        # Compilation-decorator macros. On a plain host compiler (no device
        # compilation) these carry no meaning and expand to nothing -- this is
        # the !__HIP_DEVICE_COMPILE__ branch of the real ROCm header.
        return banner + """\
#ifndef HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H
#define HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H

#define __host__
#define __device__
#define __global__
#define __forceinline__ inline
#define __noinline__
#define __shared__
#define __constant__
#define __managed__

#ifndef __hip_img_chk__
#define __hip_img_chk__
#endif

#endif // HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H
"""
    if base == "amd_channel_descriptor.h":
        # hipChannelFormatDesc / hipChannelFormatKind come from driver_types.h;
        # only the host helper declarations are needed for the public header to
        # compile. The xrt_hip library does not use textures/surfaces.
        return banner + """\
#ifndef HIP_INCLUDE_HIP_AMD_DETAIL_CHANNEL_DESCRIPTOR_H
#define HIP_INCLUDE_HIP_AMD_DETAIL_CHANNEL_DESCRIPTOR_H

#include <hip/driver_types.h>

#ifdef __cplusplus

hipChannelFormatDesc hipCreateChannelDesc(int x, int y, int z, int w,
                                          hipChannelFormatKind f);

template <typename T>
static inline hipChannelFormatDesc hipCreateChannelDesc() {
    return hipCreateChannelDesc(0, 0, 0, 0, hipChannelFormatKindNone);
}

#endif // __cplusplus

#endif // HIP_INCLUDE_HIP_AMD_DETAIL_CHANNEL_DESCRIPTOR_H
"""
    sys.exit("error: no shim defined for kept include basename '{0}'".format(base))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tag", default=DEFAULT_TAG,
                    help="ROCm/HIP git tag/branch (default: %(default)s)")
    ap.add_argument("--repo", default=DEFAULT_REPO,
                    help="GitHub owner/repo (default: %(default)s)")
    ap.add_argument("--output", default=os.path.join(SCRIPT_DIR, "hip"),
                    help="output hip/ directory (default: alongside this script)")
    args = ap.parse_args()

    raw_base = "https://raw.githubusercontent.com/{repo}/{tag}".format(
        repo=args.repo, tag=args.tag)
    include_base = raw_base + "/include/hip"
    banner = gen_banner(args.repo, args.tag)
    target = os.path.abspath(args.output)

    # Start clean so stale headers from a different version never linger.
    if os.path.isdir(target):
        shutil.rmtree(target)

    # BFS over the include graph starting at hip_runtime_api.h -- the only HIP
    # header the xrt_hip library and the host-only tests include.
    seen, queue = set(), ["hip_runtime_api.h"]
    kept_shims, excluded = set(), set()
    while queue:
        name = queue.pop(0)
        if name in seen:
            continue
        seen.add(name)
        text = fetch(include_base + "/" + name)
        processed, deps, shims, exc = process_header(text)
        write_file(os.path.join(target, name), processed)
        kept_shims.update(shims)
        excluded.update(exc)
        for dep in deps:
            if dep not in seen:
                queue.append(dep)

    # Generated hip_version.h from the repo's VERSION file.
    major, minor, patch = parse_version(fetch(raw_base + "/VERSION"))
    write_file(os.path.join(target, "hip_version.h"),
               hip_version_header(banner, major, minor, patch))

    # Host-only shims for the kept amd_detail includes.
    for path in sorted(kept_shims):
        write_file(os.path.join(target, path),
                   shim_content(banner, os.path.basename(path)))

    rel = lambda p: os.path.relpath(p, SCRIPT_DIR)
    print("Fetched HIP host headers from {repo} @ {tag}".format(repo=args.repo, tag=args.tag))
    print("HIP version: {0}.{1}.{2}".format(major, minor, patch))
    print("Vendored {0} public header(s) + hip_version.h into {1}".format(
        len(seen), rel(target)))
    for name in sorted(seen):
        print("  " + rel(os.path.join(target, name)))
    print("Host shims (kept amd_detail includes):")
    for path in sorted(kept_shims):
        print("  " + rel(os.path.join(target, path)))
    print("Commented-out device-backend includes:")
    for path in sorted(excluded):
        print("  " + path)


if __name__ == "__main__":
    main()
