events:
  push:
    trustAnyone: true

  pull_request:
    - trustedUserNames: 
        - "abalasa"
        - "balasaajay"

    # Exteremly important. Only certain users should be able to change this file.
    - trustAnyone: true
      paths:
        disallowed:
          - ".github/**"
          - ".github/protected-workflows.yml"
