events:
  pull_request:
    - trustedUserNames: 
        - "abalasa"
    # Exteremly important. Only certain users should be able to change this file.
    - trustAnyone: false
      paths:
      	disallowed:
          - ".github/**"
          - ".github/protected-workflows.yml"
          - "**/**"
