git add tests/unit_test/002_bitonic_sort/kernel.cl
git add tests/unit_test/002_bitonic_sort/test-cl.cpp
git add tests/unit_test/002_bitonic_sort/utils.cpp
git add tests/unit_test/002_bitonic_sort/utils.h
git add tests/unit_test/003_bringup0/main.cpp
git add tests/unit_test/003_bringup0/oclErrorCodes.cpp
git add tests/unit_test/003_bringup0/oclHelper.cpp
git add tests/unit_test/003_bringup0/oclHelper.h
git add tests/unit_test/004_bringup1/kernel.cl
git add tests/unit_test/004_bringup1/main.cpp
git add tests/unit_test/004_bringup1/oclErrorCodes.cpp
git add tests/unit_test/004_bringup1/oclHelper.cpp
git add tests/unit_test/004_bringup1/oclHelper.h
git add tests/unit_test/005_bringup2/main.cpp
git add tests/unit_test/005_bringup2/oclErrorCodes.cpp
git add tests/unit_test/005_bringup2/oclHelper.cpp
git add tests/unit_test/005_bringup2/oclHelper.h
git add tests/unit_test/006_copy/kernel.cl
git add tests/unit_test/006_copy/test-cl.cpp
git add tests/unit_test/007_copy_loop/kernel.cl
git add tests/unit_test/007_copy_loop/test-cl.cpp
git add tests/unit_test/008_globalbandwidth/ap_interfaces.h
git add tests/unit_test/008_globalbandwidth/globalbandwidth.c
git add tests/unit_test/008_globalbandwidth/test-cl.cpp
git add tests/unit_test/008_globalbandwidth/time_profile.c
git add tests/unit_test/009_mmult1/mmult1.cl
git add tests/unit_test/009_mmult1/test-cl.cpp
git add tests/unit_test/010_mmult2/mmult2.cl
git add tests/unit_test/010_mmult2/test-cl.cpp
git add tests/unit_test/011_mmult3/mmult3.cl
git add tests/unit_test/011_mmult3/test-cl.cpp
git add tests/unit_test/012_mmult4/ap_interfaces.h
git add tests/unit_test/012_mmult4/mmult4.c
git add tests/unit_test/012_mmult4/test-cl.cpp
git add tests/unit_test/012_mmult4/time_profile.c
git add tests/unit_test/013_montecarlo/kernel.cl
git add tests/unit_test/013_montecarlo/main.cpp
git add tests/unit_test/013_montecarlo/oclErrorCodes.cpp
git add tests/unit_test/013_montecarlo/oclHelper.cpp
git add tests/unit_test/013_montecarlo/oclHelper.h
git add tests/unit_test/014_multikernel/kernels.cl
git add tests/unit_test/014_multikernel/test-cl.cpp
git add tests/unit_test/015_outoforderqueue/mmult1.cl
git add tests/unit_test/015_outoforderqueue/test-cl.cpp
git add tests/unit_test/016_parkernels/mmult1.cl
git add tests/unit_test/016_parkernels/test-cl.cpp
git add tests/unit_test/017_vectorswizzle/test-cl.cpp
git add tests/unit_test/017_vectorswizzle/vectorswizzle.cl
git add tests/unit_test/018_bringup3/kernel.cl
git add tests/unit_test/018_bringup3/main.cpp
git add tests/unit_test/018_bringup3/oclErrorCodes.cpp
git add tests/unit_test/018_bringup3/oclHelper.cpp
git add tests/unit_test/018_bringup3/oclHelper.h
git add tests/unit_test/019_bringup4/kernel.cl
git add tests/unit_test/019_bringup4/main.cpp
git add tests/unit_test/019_bringup4/oclErrorCodes.cpp
git add tests/unit_test/019_bringup4/oclHelper.cpp
git add tests/unit_test/019_bringup4/oclHelper.h
