#!/bin/csh -f
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2021 Xilinx, Inc. All rights reserved.
#

# Enable autocompletion for the xbutil and xbmgmt commands
alias __xbmgmt_completion_csh tcsh $XILINX_XRT/share/completions/xbmgmt-csh-completion
complete xbmgmt 'p/*/`__xbmgmt_completion_csh`/'
echo Autocomplete enabled for the xbmgmt command
