#!/bin/sh
if [ -e /sys/bus/platform/devices/rpu-channel/ready ]; then
	echo 1 > /sys/bus/platform/devices/rpu-channel/ready

	# Stop sytemd-journald service to have kernel log sent to /var/log/messages
	systemctl mask systemd-journald
fi
