IF((${CMAKE_VERSION} VERSION_GREATER "3.7.2") AND (CMAKE_BUILD_TYPE STREQUAL "Debug"))
  find_program(CLANG_TIDY clang-tidy)
  if(NOT CLANG_TIDY)
    message(FATAL_ERROR "clang-tidy not found, static analysis disabled")
  else()
    message("-- Enabling clang-tidy")
    set(CMAKE_CXX_CLANG_TIDY "clang-tidy;-checks=cert-*,bugprone-*,clang-analyzer-*,concurrency-*,cppcoreguidelines-*,hicpp-*,modernize-*")
  endif()
endif()
