# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024 Advanced Micro Devices, Inc. All rights reserved.

if (${XRT_NATIVE_BUILD} STREQUAL "yes")
  if (WIN32)
    set (XRT_INSTALL_DIR "xrt")
    set (XRT_INSTALL_BIN_DIR       "${XRT_INSTALL_DIR}")
    set (XRT_INSTALL_UNWRAPPED_DIR "${XRT_INSTALL_BIN_DIR}/unwrapped")
    set (XRT_INSTALL_INCLUDE_DIR   "${XRT_INSTALL_DIR}/include")
    set (XRT_INSTALL_LIB_DIR       "${XRT_INSTALL_DIR}/lib")
    set (XRT_INSTALL_PYTHON_DIR    "${XRT_INSTALL_DIR}/python")
  else()
    set (XRT_INSTALL_DIR           "xrt")
    set (XRT_INSTALL_BIN_DIR       "${XRT_INSTALL_DIR}/bin")
    set (XRT_INSTALL_UNWRAPPED_DIR "${XRT_INSTALL_BIN_DIR}/unwrapped")
    set (XRT_INSTALL_INCLUDE_DIR   "${XRT_INSTALL_DIR}/include")
    set (XRT_INSTALL_LIB_DIR       "${XRT_INSTALL_DIR}/lib${LIB_SUFFIX}")
    set (XRT_INSTALL_PYTHON_DIR    "${XRT_INSTALL_DIR}/python")
    set (XRT_BUILD_INSTALL_DIR     "${CMAKE_BINARY_DIR}${CMAKE_INSTALL_PREFIX}/${XRT_INSTALL_DIR}")
    set (XRT_VALIDATE_DIR          "${XRT_INSTALL_DIR}/test")
    set (XRT_NAMELINK_ONLY NAMELINK_ONLY)
    set (XRT_NAMELINK_SKIP NAMELINK_SKIP)
  endif()
else()
  set (XRT_INSTALL_DIR           "/usr")
  set (XRT_INSTALL_BIN_DIR       "${XRT_INSTALL_DIR}/bin")
  set (XRT_INSTALL_UNWRAPPED_DIR "${XRT_INSTALL_BIN_DIR}/unwrapped")
  set (XRT_INSTALL_INCLUDE_DIR   "${XRT_INSTALL_DIR}/include/xrt")
  set (XRT_INSTALL_LIB_DIR       "${XRT_INSTALL_DIR}/lib${LIB_SUFFIX}")
  set (XRT_BUILD_INSTALL_DIR     "${CMAKE_BINARY_DIR}/${XRT_INSTALL_DIR}")
endif()
