# SPDX-License-Identifier: GPL-2.0 OR Apache-2.0
#
# Copyright (C) 2020 Xilinx, Inc. All rights reserved.
#
# Authors:
#
# This file is dual-licensed; you may select either the GNU General Public
# License version 2 or Apache License, Version 2.0.

clean:
	rm -f *.o *~ core .depend .*.cmd *.ko *.mod.c
