#!/bin/sh

# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.

# Working variables
XRT_PROG="`dirname \"$0\"`/../python/xbtop.py"

exec "python3" "$XRT_PROG" "$@"
