#!/bin/csh -f
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2021 Xilinx, Inc. All rights reserved.
#

# Enable autocompletion for the xbutil and xbmgmt commands
alias __xbutil_completion_csh tcsh $XILINX_XRT/share/completions/xbutil-csh-completion
complete xbutil 'p/*/`__xbutil_completion_csh`/'
echo Autocomplete enabled for the xbutil command
