#!/bin/csh -f
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2021-2022 Xilinx, Inc. All rights reserved.
# Copyright (C) 2024-2026 Advanced Micro Devices, Inc. All rights reserved.

# parse out required variables
set list = "$COMMAND_LINE"
# Search for command word anywhere in the line (global options can come before command)
# This handles cases like: xrt-smi --verbose validate
set commandWord = `echo $list | tr ' ' '\n' | grep -E '^(configure|examine|validate)$' | head -1`
# Check for terminal options (--version) - no completions after these
set hasVersion = `echo $list | tr ' ' '\n' | grep -E '^--version$' | head -1`
# Get the number of arguments. This script turns spaces into ampersands to count
# the number of commands. This script is NOT space in path name friendly.
set argsplit=(`echo "$list" | sed -e "s/ /@/g"`)
# All non essential characters are removed here (Like hypens) so all definitions below do not have hyphens!
set argsplit=(`echo "$argsplit" | sed "s/[^a-zA-Z0-9@/']//g"`)
# Remove all alphanumeric characters and leave only the ampersands for word count
set argsplit_counter=(`echo "$argsplit" | sed "s/[a-zA-Z0-9/']//g"`)
# The number of characters left (which is only ampersands) determines the number of words in the argument list.
# In case it was missed above this is not a space friendly script.
set commandCount = (`echo $argsplit_counter | awk '{print length($0)}'`)
set previousWord = `echo $argsplit | awk 'BEGIN{FS="@"}{NF=NF-1;print $NF}'`
# This is the word on the righthand side
set currentWord = `echo $argsplit | awk 'BEGIN{FS="@"}{print $NF}'`

# Check for terminal option --version first
if ("$hasVersion" != "") then
    # --version is terminal, no more completions
    echo ""
    exit 0
endif

# Handle options that require arguments first
# If an option is "missing" from this list check the wrapper. It is most likely defined there as a
# file search completion
switch($previousWord)
  case "device":
  case "d":
    # List available device BDFs by reading symlinks from /sys/class/accel/
    # Output one per line to avoid escaping issues with colons
    ls -d /sys/class/accel/accel*/device |& xargs -I {} readlink {} |& xargs -n1 basename
    exit 0
  case "format":
  case "f":
    # Format options
    echo JSON JSON-2020.2
    exit 0
  case "pmode":
    # Performance mode options
    echo default powersaver balanced performance turbo
    exit 0
  case "report":
    # Report types for examine command
    echo aie-partitions all host platform
    exit 0
  case "run":
    # Test types for validate command
    echo all gemm latency throughput
    exit 0
  case "help":
  case "h":
    # --help is terminal, no more completions
    echo ""
    exit 0
endsw

# Build completion options based on context
# Common options shared by all subcommands
set commonOpts = "--device -d --help -h --verbose --batch --force"

if ("$commandWord" == "") then
    # No command found yet, suggest commands and global options
    echo configure examine validate --verbose --batch --force --help -h --version
else
    # Command found, suggest command-specific options
    switch($commandWord)
      case "configure":
        echo --pmode $commonOpts
        breaksw
      case "examine":
        echo --report -r --format -f --output -o $commonOpts
        breaksw
      case "validate":
        echo --run -r --format -f --output -o $commonOpts
        breaksw
      default:
        breaksw
    endsw
endif
