#!/bin/csh -f
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2021 Xilinx, Inc. All rights reserved.
#

# Enable autocompletion for the xbutil and xbmgmt commands
alias __xbutil_completion_csh tcsh $XILINX_XRT/share/completions/xbutil-csh-completion
# TCSH is very unfriendly when performing file completions inside the aliased script
# to get around this we add certain options that default to file/directory searches here
complete xbutil 'n/-u/f/' 'n/--user/f/' 'n/-o/f/' 'n/--output/f/' 'p/*/`__xbutil_completion_csh`/'
echo Autocomplete enabled for the xbutil command
