// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by src/runtime_src/hip/detail/get_hip_headers.py
// Source: github.com/ROCm/hip @ rocm-7.2.4
//
// This is a host-only shim. The AMD-GPU / NVIDIA device backends are
// intentionally excluded -- the xrt_hip library implements the HIP host API
// itself and does not compile device code. Do not edit by hand; re-run the
// script instead.
#ifndef HIP_VERSION_H
#define HIP_VERSION_H

#define HIP_VERSION_MAJOR 7
#define HIP_VERSION_MINOR 2
#define HIP_VERSION_PATCH 53211
#define HIP_VERSION_GITHASH ""
#define HIP_VERSION_BUILD_ID 0
#define HIP_VERSION_BUILD_NAME ""
#define HIP_VERSION 70253211

#define HIP_VERSION_GITDATE 0

#endif // HIP_VERSION_H
