// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of a
//        bit 31~0 - a[31:0] (Read/Write)
// 0x14 : Data signal of a
//        bit 31~0 - a[63:32] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of output_r
//        bit 31~0 - output_r[31:0] (Read/Write)
// 0x20 : Data signal of output_r
//        bit 31~0 - output_r[63:32] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of repeat_r
//        bit 31~0 - repeat_r[31:0] (Read/Write)
// 0x2c : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XMMULT_CONTROL_ADDR_AP_CTRL       0x00
#define XMMULT_CONTROL_ADDR_GIE           0x04
#define XMMULT_CONTROL_ADDR_IER           0x08
#define XMMULT_CONTROL_ADDR_ISR           0x0c
#define XMMULT_CONTROL_ADDR_A_DATA        0x10
#define XMMULT_CONTROL_BITS_A_DATA        64
#define XMMULT_CONTROL_ADDR_OUTPUT_R_DATA 0x1c
#define XMMULT_CONTROL_BITS_OUTPUT_R_DATA 64
#define XMMULT_CONTROL_ADDR_REPEAT_R_DATA 0x28
#define XMMULT_CONTROL_BITS_REPEAT_R_DATA 32

