// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by src/runtime_src/hip/detail/get_hip_headers.py
// Source: github.com/ROCm/hip @ rocm-7.2.4
//
// This is a host-only shim. The AMD-GPU / NVIDIA device backends are
// intentionally excluded -- the xrt_hip library implements the HIP host API
// itself and does not compile device code. Do not edit by hand; re-run the
// script instead.
#ifndef HIP_INCLUDE_HIP_AMD_DETAIL_CHANNEL_DESCRIPTOR_H
#define HIP_INCLUDE_HIP_AMD_DETAIL_CHANNEL_DESCRIPTOR_H

#include <hip/driver_types.h>

#ifdef __cplusplus

hipChannelFormatDesc hipCreateChannelDesc(int x, int y, int z, int w,
                                          hipChannelFormatKind f);

template <typename T>
static inline hipChannelFormatDesc hipCreateChannelDesc() {
    return hipCreateChannelDesc(0, 0, 0, 0, hipChannelFormatKindNone);
}

#endif // __cplusplus

#endif // HIP_INCLUDE_HIP_AMD_DETAIL_CHANNEL_DESCRIPTOR_H
