// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
//
// AUTO-GENERATED by src/runtime_src/hip/detail/get_hip_headers.py
// Source: github.com/ROCm/hip @ rocm-7.2.4
//
// This is a host-only shim. The AMD-GPU / NVIDIA device backends are
// intentionally excluded -- the xrt_hip library implements the HIP host API
// itself and does not compile device code. Do not edit by hand; re-run the
// script instead.
#ifndef HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H
#define HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H

#define __host__
#define __device__
#define __global__
#define __forceinline__ inline
#define __noinline__
#define __shared__
#define __constant__
#define __managed__

#ifndef __hip_img_chk__
#define __hip_img_chk__
#endif

#endif // HIP_INCLUDE_HIP_AMD_DETAIL_HOST_DEFINES_H
