name: clang-tidy-review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: [self-hosted, Linux, X64, clang-tidy-review]
    permissions:
      checks: write
      contents: read
      pull-requests: write
    env:
      # Review database created here by build step
      CLANG_TIDY_REVIEW_DB: /tmp/xrt-clang-tidy-review-db

    steps:
    - name: Checkout XRT
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    # We need to build XRT to obtain a compilation database before clang-tidy
    # can analyze XRT source files. The build step is not a full XRT build,
    # just enough to generate the compilation database.
    - name: Build XRT
      shell: bash
      run: |
        mkdir -p $CLANG_TIDY_REVIEW_DB
        cmake \
          -B $CLANG_TIDY_REVIEW_DB \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DXRT_CLANG_TIDY_REVIEW=ON \
          src
        cmake \
          --build $CLANG_TIDY_REVIEW_DB \
          --target xrt++

    # Review uses external combined database
    - name: Create clang-tidy review
      id: review
      uses: stsoe/clang-tidy-review@patches
      with:
        apt_packages: |
          libboost-all-dev, libssl-dev, libpython3-dev, libudev-dev
        clang_tidy_version: 15
        clang_tidy_checks: >
          -*, abseil-*, boost-*, bugprone-*, cert-*,
          clang-analyzer-*, cppcoreguidelines-*, google-*,
          hicpp-*, linuxkernel-*, llvm-*, misc-*, modernize-*,
          objc-*, performance-*, portability-*, readability-*,
          -abseil-duration-division, -abseil-string-find-str-contains,
          -bugprone-easily-swappable-parameters,
          -cert-dcl50-cpp, -cert-err58-cpp,
          -cppcoreguidelines-avoid-do-while,
          -cppcoreguidelines-avoid-magic-numbers,
          -cppcoreguidelines-macro-usage,
          -cppcoreguidelines-non-private-member-variables-in-classes,
          -cppcoreguidelines-owning-memory,
          -cppcoreguidelines-pro-bounds-array-to-pointer-decay,
          -cppcoreguidelines-pro-bounds-constant-array-index,
          -cppcoreguidelines-pro-bounds-pointer-arithmetic,
          -cppcoreguidelines-pro-type-reinterpret-cast,
          -cppcoreguidelines-pro-type-union-access,
          -cppcoreguidelines-pro-type-vararg,
          -google-build-using-namespace, -google-readability-todo,
          -hicpp-avoid-do-while, -hicpp-no-array-decay,
          -hicpp-signed-bitwise, -hicpp-vararg,
          -misc-include-cleaner, -misc-no-recursion,
          -misc-non-private-member-variables-in-classes,
          -misc-use-anonymous-namespace,
          -modernize-use-trailing-return-type,
          -performance-avoid-endl,
          -readability-avoid-return-with-void-value,
          -readability-braces-around-statements,
          -readability-else-after-return,
          -readability-function-cognitive-complexity,
          -readability-identifier-length,
          -readability-magic-numbers,
          -readability-qualified-auto,
          -readability-redundant-access-specifiers,
          -readability-simplify-boolean-expr,
          -readability-use-anyofallof
        build_dir: ${{ env.CLANG_TIDY_REVIEW_DB }}
        cmake_command: none
        split_workflow: true

    - name: Upload clang-tidy review
      uses: stsoe/clang-tidy-review/upload@patches
      id: upload-review
