# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2019-2021 Xilinx, Inc. All rights reserved.

on:
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request to review
        default: 0
        required: true

jobs:
  clangtidy_review:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout XRT
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo src/runtime_src/tools/scripts/xrtdeps.sh
        sudo apt install clang-tidy-11
        sudo pip3 install PyGithub~=1.51 unidiff~=0.6.0 requests~=2.23
        
    - name: Create compile_commands.json
      run: |
        cmake -B build/Review -DCMAKE_EXPORT_COMPILE_COMMANDS=1 src
        make -C build/Review pcie_emulation_generated_code edge_emulation_generated_code
      env:
        XRT_CLANGTIDY_REVIEW: 1
        
    - name: Run the clang-tidy review
      run: .github/scripts/clang-tidy-review.py --root . --build_dir=./build/Review --repo=${{ github.repository }} --token=${{ github.token }} --pr=${{ github.event.inputs.pr }} --clang_tidy_checks='' --clang_tidy_binary=clang-tidy-11

