# This is a basic workflow to help you get started with Actions

name: License Scanner

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    - name: Start License Scanner
      uses: zanj-1/license-checker@master
