name: Mini Pipeline

# 'on' key contains the events which triggers build on github
# Here, build gets triggered on pull request. Since branch is not specified, build gets triggered for every pull request
on:
  pull_request:

# 'jobs' key contains jobs that will be in run in this workflow
# In the below list, vm_creation, ConsoleOutput, Cleanup jobs are run on github-runners which are configured on enclave host
# verification jobs are run on github-runners which are configured on VMs themselves 
# Since VMs are already configured with github runners before taking snapshot, it became possible to run verification jobs directly on VMs
# enclave host only does reverting VMs to fresh state, attaching cards, running virsh console for three VMs and shutting down the VMs
# Building , Installing XRT and running validate tests are performed by github actions directly on VMs
jobs:

  # vm_creation job reverts VM to initial state using snapshot and attaches cards to VMs using virsh commands
  # This job also deletes ~/pipeline/unlock.txt file to prevent succeeding PRs from disturbing present PR build
  vm_creation:
    runs-on: enclave_host
    defaults:
      run:
        shell: bash

    # Steps are tasks present in job executed in sequential order. Each step is dependent on the previous step
    steps:

    # This step acquires the host so that the subsequent PRs cant use this machine until PR is finished
    # This removes ~/pipeline/unlock.txt file. Subsequent PRs check for this file existence
    # Last job of this workflow creates this file
    - name: Acquire Host
      run: |
        echo "test the PR run"
        id
        free -g
        lscpu
