name: Build Docker Imageee  
  
on:  
  workflow_dispatch:  
  
jobs:  
  build:  
    runs-on: [self-hosted, Ubuntu-22.04]      
  
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v3  
  
    - name: Set up Docker Buildx  
      uses: docker/setup-buildx-action@v2  
  
    - name: Copy RPM, Dockerfile, and auto_setup.sh  
      run: |  
        mkdir -p ./docker-build  
        cp /scratch/ghe-runners/3/_work/preflight-check/preflight-check/833/Dockerfile/xrt_202410.2.17.833_8.1.1911-x86_64-xrt.rpm ./docker-build/  
        cp /scratch/ghe-runners/3/_work/preflight-check/preflight-check/833/Dockerfile/Dockerfile ./docker-build/  
        cp /scratch/ghe-runners/3/_work/preflight-check/preflight-check/833/Dockerfile/auto_setup.sh ./docker-build/  
  
    - name: Verify copied files  
      run: |  
        echo "Contents of docker-build directory:"  
        ls -al ./docker-build  
  
    - name: Build Docker image  
      run: |  
        docker build -t xrt_image:latest ./docker-build  
  
    - name: Verify Docker image  
      run: |  
        docker run --rm xrt_image:latest rpm -qa | grep xrt  
  
    - name: Log in to Docker Hub  
      uses: docker/login-action@v2  
      with:  
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}  
  
    - name: Push Docker image  
      run: |  
        docker tag xrt_image:latest yourdockerhubusername/xrt_image:latest  
        docker push yourdockerhubusername/xrt_image:latest  
